#!/bin/env bash
#using while loop and if statement to display Best school 10 times and on the 9th time also displays Hi on a new line
i=1
while [ $i -le 10 ]
do 
echo "Best School"
 i=$(($i+1 )) 
 if [ $i == 10 ]
 then echo "Hi" 
 fi
 done
