#!/usr/bin/env bash
#using while loop and if statement to display Best school 10 times and on the 9th time also displays Hi on a new line
i=1
while [ $i -le 10 ]
do 
echo "Best School" 
 if [ $i == 9 ]
 then echo "Hi" 	 
 fi
 i=$((i+1))
 done
