#!/usr/bin/env bash
#that is the question
f=school
   if [ -e "$f" ]
     then
     echo "school file exists" 
      else
      echo "school file does not exist"	      
      exit
   fi
     if [ -s "$f" ]
    then
     echo "file is not empty"
     else 
     echo "file is empty"
fi
  if [ -f "$f" ]
  then 
   echo "school file is regular file"
  else 
   :
fi
